### PR TITLE
Fix CLI bug with generation project in subdirectory

### LINKED ISSUE #366: lotus new . creates unwanted subdirectory in some cases
Version: HEAD

If i run the `lotus new .` command to create a new project inside an existing directory, it creates the project in a new subdirectory with the same name as the root dir instead of using the root dir itself. 

Steps to reproduce:
1. create a folder e.g. lotus_test and cd into that directory
2. create a Gemfile as shown below
3. run bundle install
4. run bundle exec lotus new .

Subdirectory is created.

As @AlfonsoUceda suggested the error may lay here:
https://github.com/lotus/lotus/commit/d9ca958bfeeec98893d478b802ce80a141f168ea#diff-3394769438b4229c5c6d442abe4e5cbaR29

Content of Gemfile:
```
source "https://rubygems.org"
ruby "2.2.3"

gem "bundler"
gem "rake"
gem "thin"

gem "lotusrb", github: "lotus/lotus"
gem "lotus-controller", github: "lotus/controller"
gem "lotus-view", github: "lotus/view"
gem "lotus-helpers", github: "lotus/helpers"
gem "lotus-validations", github: "lotus/validations"
gem "lotus-router", github: "lotus/router"
gem "lotus-utils", github: "lotus/utils"
```

### PR DESCRIPTION
**Pull request by aderyabin**
PR should resolve #366

### CODE REVIEW

**Comment by joneslee85** [comment]
@aderyabin do you think if you could get a test for this? TIA

File: test/commands/new/container_test.rb [hunk 1]
```diff
@@ -41,6 +41,20 @@
       end
     end
 
+    it 'application name is a point' do
+      with_temp_dir do |original_wd|
+       command = Lotus::Commands::New::Container.new({}, '.')
+        capture_io { command.start }
+        Dir.chdir('.') do
+          actual_content = File.read('.env.development')
+          assert actual_content.include?('TESTAPP_DATABASE_URL="file:///db/testapp_development"')
```
Comment (joneslee85) [inline test/commands/new/container_test.rb]: can you please use `must_include` instead? cheers

File: test/commands/new/container_test.rb [hunk 2]
```diff
@@ -41,6 +41,20 @@
...
+
+          actual_content = File.read('.env.test')
+          assert actual_content.include?('TESTAPP_DATABASE_URL="file:///db/testapp_test"')
```
Comment (joneslee85) [inline test/commands/new/container_test.rb]: same as above

File: test/commands/new/container_test.rb [hunk 3]
```diff
@@ -41,6 +41,20 @@
       end
     end
 
+    it 'application name is a point' do
```
Comment (joneslee85) [inline test/commands/new/container_test.rb]: please use `describe` here and use `it` to state the outcome of the behaviour
